sudo: required
language: python
services:
  - docker
python:
- '2.7'
matrix:
  include:
  - os: linux
    dist: trusty
    after_success:
    - pip install codecov -e .
    - coverage run --source=src/sysl -m py.test
    - codecov
  - os: osx
    osx_image: xcode8.3
    language: generic
    before_install:
    - brew update
    - brew list python >/dev/null 2>&1 || brew install python
    - brew list gradle >/dev/null 2>&1 || brew install gradle
    - export PATH=/usr/local/opt/python/libexec/bin:$PATH
env:
  matrix:
  - SYSL_PLANTUML=http://www.plantuml.com/plantuml
  global:
  - secure: RjMrJ7eu0rZxVb4+ytSoMy1kxnTeFnpSUo1SWu92B3KlQuIJb4nAE7x2qY4BNzh+d+eUKaeFIlACW1pEN87MYsPNp5wEG5F88Cbp+LELzXfUhMAWrj1LJXFLasHESPipye4gWUkRgUSlVjO2fdPwcM/9A7OLSt/vESBeTTuidrjmtebckX71mZp94Y029qSeXO71Oq+xc/O68Sh8KDg1FD1GSWddA5e2vV8GbJCPHtJ5IgWlqVm58gZQHJUT9pzkvrGws9UtMWeWMLHb227/IxDLE/QYNUn2pKMhz0frqq6Eq8mjCtFYX0wDLtwiBasYCRErU9Pb5zxYSJy3IDqiHDZ5Z/CT1uyplr53EddTUVC95UOCJMq73YKp0tUP5kNEX6v0RMzX54FGEelJ7Pj7AakJYqcVqFlXurMlWvakPBV5KjyLFbsFcWaAvqqgyCgGSlwylAmTGh0n8/RjD2Mw6pTDWYTPlvIzLJi52X4KmWR0ZT2+nqUY798vnO4WMTsmWnb0zi7BHX+u/rPIB20dfYM0lM8h1LuHg1oEYrgoHz0ZnfgP1jyXr/qkYJ31hFRR6vwvJjAHKn0FbAy4KPFNCWSIS8VlLegIjW1UxQddmqmhs60m6Sqg8JQMsm6DLxNb/bbTGSIOBQaVChhxrKaBcVnKNl8lGbdipPD3s18SIwU=
  - secure: Gm5kztwSXiB2sKd8x+plyC9jpDMGhGo8HT9icHheazRNx2ybGI+612CvBCuP2aLQEJ0wy9Ld4F2TOFAzcd8P+/NbtfIQ8HsdoOqqWQCwSwQlgwHhpA47aVKjKnevx7mQBIWuZmvSf6UTaHilNOhXB22P0nZ36vBxOHcgVcMGiHDMK3CRkyvAFMvOkVsOTu3LE95xEn6Eu7sdTWTxeOmSBuGhVCAiJa1Q6T3CiH3y5W7uU8o3O1VI/8ZKcxoxU6HtU2iodRaTh8s/uPh77voU7iGxWfGGBiVdJbWCxAkEZ5IkCMrZuXEz+y09Mk+sn2iqiHAdiqgQvUUOQcOGMeyFmAxI3R430Nd3UOTJziCYYzBKuk8f7dMvtACbcoUPGupWWGnGARutemLEE6Hsm1wYmbhg8OhfRmZNL8+9ZLvK9/Daq9Z0zNzxXaFJHZaTLldpsu5Fh8nPe7hc0ov1+1Qj1rgukZ1AtETTVo9OXN8Nc4aLr09BuLvjOyP5VM8hYEt8mLOd10sePDLYlHXg/yzai638pBJqfNebEQJD+4Ky+T6EKVqVoGnDHQiKXiYbrtE9zoTlxaMwyFDOipOwdPrfOl686Ey1syd7HjXkHqY4qdfMVGkcqOgPEhFJxrk9n14XKT7kxTB/w1UJt27IRldt1asIcxlN4szRWMMT/VAvIqY=
install:
- pip install . pytest flake8
script:
- flake8
- pytest
- gradle test -b test/java/build.gradle
before_deploy:
- python setup.py sdist bdist_wheel
- gradle build -b src/libs/java/build.gradle :jar
- docker build -t "$DOCKER_IMAGE" -f Dockerfile .
deploy:
- provider: releases
  draft: true
  tag_name: "$TRAVIS_TAG"
  name: Sysl $TRAVIS_TAG
  api_key:
    secure: TkWCKFPiDVTbOup9rQi+VceTbXHWoHphMzB6ZJ3bBGPZsHf2rZeVdknQ/9jcUHiYdnhvFspKpp2Dn2e58At8IJTYRx3F93uBCFu9om/U2UtphccO1X6rZw0rcCVTHIuosvyp7iec3qxxTwmnIliQvHnnVJgRzt6IKw/jjDyMZzvBrch52xQV5eDOacW2PwfMJ3Q03UI+fM6C8F/F7RW1T7k+jBcXTzp4mr1mPm3zYvvKBjFPLQk4+8lT9Nbh+FGAXwc6SVl1ue9jQIH3zK4ED4y9uQcdFaz253QqXpnKCl9kJhyYnlsKCAnqqGm/X9DrZUqxYWuSMz9DWA7T+ulI0LO1w4S/DNkZ4ksaGYuwHqVTBSErEC1cJZgSRSsedjaENZgav/FUFL4+3WQf3wP+vM8UzGVJsUJEWlx9DFW61btRwBEJuflVaL6HqhDBebv1sa/8vskcyaiMszxr7V58/Kh3AGC3KBX6sqU0Oc5KXWwgsYiQbNIctFZR0EbcH4aO2yoQO5RPJW8KkaJgMYec6/si/2jT1KxHsA2PAE7GQOOyhTIrTc0AEAA1/6rb8ksIlREOObv4YZFdNYLP3Kv3PGECbHgDh9Ee15MtnezHQqY9qwbh2+0T6i0heHa/1XgNOiG/Y3OpriB1vil/yerH1FJVr6i73xXAyRpgnl4EC7I=
  file_glob: true
  file:
  - dist/*
  - src/libs/java/build/libs/*
  skip_cleanup: true
  prerelease: true
  on:
    repo: anz-bank/sysl
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"
- provider: pypi
  user: sysl.usr
  skip_cleanup: true
  distributions: sdist bdist_wheel
  password:
    secure: j9NRzqbk/hq9U25Ig5r2aA1+Y/asG2jqP4T35x4cwdosE3r4i9delxG0ZyLa4D44OYM7joIPdMyr9khlfK5HBXqNC9ZzhlDyYlg5/LJmsM4TeS5KaKyPL89bqDAX2NhNgVjb8J68XsKkizYjzVeKbPl5UYdoyv7t4yLytlsAjRBBYmIo5mJ9Obx1Hb+nUP7Ny4Pwl43Oxkr2qS91iD074V4B0czHjMvtizqttOGTr81TzPbuDsd4/DW8GVQF0gPazg1/UqhN37oAKpIH9k5u4ScrKQkUGDO1eOEkwogTqOAcOTu91AZST/1OHN2ZRcMtvcyY1QJWq88s9p9DIWqsSK42bb4L0SziNa23hvFUpkaxsnl6MCLPaHP2zpo3cyKOGmWT6JElv9hJBVFimCG1V1b/YNHVuoNfz6J3gbW8ILw9e6vebfQRHHqAwBQWtRilHnO5jRcLRIvBSZyApYw6rBUGtuDD2GbXwcFVbIde1xqfvt3dlB/ZC4PiyXqdwAKadjTxycP/Aexzg4YpoWnHUS+aeFJVy+Qb/3H3lZLNIz9zRqCnIvpIR0+hzTgNVuVRrr1WlupIPxY47+cy7s0dhi3gf+/j+YxNgKnTlZin+RvcU9+49CL9DYyMYYRA/RauJi/pa7hbEvxtY/AykcvRpQcv4Crl1mTOn+zqvrFdCDw=
  on:
    repo: anz-bank/sysl
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"
- provider: script
  script: gradle -b src/libs/java/build.gradle bintrayUpload
  skip_cleanup: true
  on:
    repo: anz-bank/sysl
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"
- provider: script
  script: docker login -u "$DOCKER_USER" -p "$DOCKER_PASS" && docker push "$DOCKER_IMAGE"
  on:
    repo: sahejsingh/sysl
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"
