dist: trusty
sudo: false
language: python
python:
  - "2.7"
branches:
  only:
  - /.*/
env:
  - SYSL_PLANTUML=http://www.plantuml.com/plantuml
install:
  - pip install . pytest flake8
  - pip install --upgrade six
script:
  - flake8
  - pytest
  - cd test/java && /usr/local/gradle/bin/gradle run
