environment:
  PYTHON: "C:\\Python27"
  SYSL_PLANTUML: http://www.plantuml.com/plantuml

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "pip install --upgrade setuptools"
  - "pip install . pytest flake8"

build: off

test_script:
  - "pytest"
  - "flake8"
